name: Build Custom APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'flutter/**'
      - '.github/workflows/build_custom_apk.yml'

env:
  SCITER_RUST_VERSION: "1.75"
  RUST_VERSION: "1.75"
  CARGO_NDK_VERSION: "3.1.2"
  NDK_VERSION: "r27c"
  VERSION: "1.4.1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'
          
      - name: Disable Flutter telemetry
        run: flutter config --no-analytics

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ env.NDK_VERSION }}
          add-to-path: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
               clang \
               cmake \
               curl \
               gcc-multilib \
               git \
               g++ \
               g++-multilib \
               libgtk-3-dev \
               libpam0g-dev \
               libunwind-dev \
               nasm \
               ninja-build \
               pkg-config \
               wget
          flutter pub get

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: "rustfmt"

      - name: Install cargo-ndk
        run: cargo install cargo-ndk --version ${{ env.CARGO_NDK_VERSION }} --locked

      - name: Build Rust for Android
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          ./flutter/ndk_arm64.sh
          ./flutter/ndk_arm.sh

      - name: Build APK (Custom Name)
        run: |
          chmod +x flutter/build_android_custom.sh
          ./flutter/build_android_custom.sh

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: custom-apk
          path: flutter/build/app/outputs/flutter-apk/*.apk
