name: Build Custom APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'flutter/**'
      - '.github/workflows/build_custom_apk.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          channel: 'stable'

      - name: Install dependencies
        run: |
          sudo apt-get -y install clang cmake ninja-build pkg-config libgtk-3-dev
          flutter pub get
          
      - name: Disable Flutter telemetry
        run: flutter config --no-analytics

      - name: Build APK (Custom Name)
        run: |
          chmod +x flutter/build_android_custom.sh
          cd flutter && ./build_android_custom.sh

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: custom-apk
          path: flutter/build/app/outputs/flutter-apk/*.apk
